# Generated by Django 2.0.7 on 2018-07-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('USD', models.FloatField()),
                ('JPY', models.FloatField()),
                ('BGN', models.FloatField()),
                ('CZK', models.FloatField()),
            ],
        ),
    ]
